### ISSUE TITLE
cosutrainer not recognizing osu

### ISSUE THREAD

**Issue by chicco-carone** [hwsmm/cosutrainer#3]
I installed cosu trainer from the official arch repo on my system and after that i got osumem ran it as sudo and it got no issues. I set the enviroment variable with my osu path (osu installed with this script https://github.com/NelloKudo/osu-winello) and after launching the gui for osu trainer in the terminal it doesn't recognize the game.

System info from lutris
[System]
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          6.2.12-zen1-1-zen
Desktop:         KDE
Display Server:  x11

[CPU]
Vendor:          GenuineIntel
Model:           11th Gen Intel(R) Core(TM) i5-11600K @ 3.90GHz
Physical cores:  6
Logical cores:   12

[Memory]
RAM:             15.5 GB
Swap:            4.0 GB

[Graphics]
Vendor:          NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce RTX 2060/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 530.41.03
OpenGL Core:     4.6.0 NVIDIA 530.41.03
OpenGL ES:       OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan:          Supported

**Comment by hwsmm** [comment]
What's the output of `cat /tmp/osu_path` with `osumem` and osu! running?

**Comment by chicco-carone** [comment]
This is the output that i got `[chicco@ArchChicco cosu-trainer-bin]$ cat /tmp/osu_path
1511716/mary x jon-YAKITORY - Koko de Ikiteru (TV Size) (Zekk) [Aqua's Normal].osu[chicco@ArchChicco cosu-trainer-bin]$ 
`
![Screenshot_20230509_175756](https://github.com/hwsmm/cosutrainer/assets/66080458/a1453c8a-ba86-4359-a63b-c9faa0ca6687)

**Comment by hwsmm** [comment]
What's the value of OSU_SONG_FOLDER variable?

**Comment by hwsmm** [comment]
Something's broken with your osu, I guess

Do you have a folder named `1511716` in your Songs folder? and what's the value of OSU_SONG_FOLDER variable

**Comment by chicco-carone** [comment]
I downloaded most of my beatmaps with batch beatmap downloader and that tool names the file of the beatmap only the beatmap number id so my songs folder is filled with folders named by numbers.

**Comment by chicco-carone** [comment]
I managed to get cosu-trainer working redoing every step and now it works without issues.
Just want to tell you some things that maybe you can add in the readme to make it easier for new users because in my opinion it lacks some stuff. I started using linux 1 yr ago and i still had some issues.
In the end you could specify in the path for the songs folder to use the backslash like the terminal does for the path of osu because the folder is named osu! and that ! requires the backslash (i think i missed that so it wasn't working) so specifing it could be useful to new users and you could explain a bit better that the variable needs to be set every time or added to .bashrc.
In my opinion adding these things in the readme would make it easier to start using.
Sorry for opening this issue but i had this issue on multiple pcs after resetting them so i thought there was an issue that i didn't know because i reinstall everything the same after resetting.
Thanks for your time.

**Comment by chicco-carone** [comment]
I wanna add just another thing that i just noticed. I used to open cosu trainer by typing in my search bar cosu-trainer and it says launch cosu-trainer but i just noticed that if i do that it doesn't recognize the game but if i do the same command in the terminal it launches without issues and recognizes the game.
[2023-05-11 15-40-43.zip](https://github.com/hwsmm/cosutrainer/files/11452792/2023-05-11.15-40-43.zip)
Its a zip with a video of the issue

**Comment by hwsmm** [comment]
Probably you just have OSU_SONG_FOLDER set in the terminal, but not in your desktop session..?

**Comment by hwsmm** [comment]
With the new release (0.6), you can set Songs folder with `echo "/put/Songs/folder" > ~/.cosu_songsfd`, let me know if it works well or not!

**Comment by chicco-carone** [comment]
Sorry for not responding i forgot about this. After the new update it works without issues on multiple installs of arch. 
I wanted to suggest something, in the osu-trainer for windows when you increase the speed it calculates the right ar/od and it would be a great addition since doing it manually isn't as accurate
