### ISSUE TITLE
osumem not reading properly

### ISSUE THREAD

**Issue by qubiX00** [hwsmm/cosutrainer#4]
I decided to try this since i remember the convinence of such program on windows, and while it sometimes reads properly, it most of the time fails, here's an example:

```
Current locale: pl_PL.UTF-8
New locale: C.UTF-8
/home/olek/.local/share/osu-wine/osu!/Songs/942642 Nanahira - Chikatto Chika Chika (1)/Nanahira - Chikatto Chika Chika (Agatsu) [Sotarks' 1+2 IQ].osu[Extra].osunce Number o Tomo ni (apoq) [Wanna Dance].osu: No such file or directory
Failed reading!
/home/olek/.local/share/osu-wine/osu!/Songs/357632 Nanahira - Shakunetsu Candle Master Tomoshi/Nanahira - Shakunetsu Candle Master Tomoshi (Taikuta) [Extra].osunce Number o Tomo ni (apoq) [Wanna Dance].osu: No such file or directory
Failed reading!
/home/olek/.local/share/osu-wine/osu!/Songs/942642 Nanahira - Chikatto Chika Chika (1)/Nanahira - Chikatto Chika Chika (Agatsu) [Sotarks' 1+2 IQ].osu[Extra].osunce Number o Tomo ni (apoq) [Wanna Dance].osu: No such file or directory
Failed reading!
```

I hope you fix this

Here is my system info:
**SYSTEM INFO**
OS: Arch Linux
Arch: x86_64
Kernel: 6.3.1-zen1-1-zen
WM: bspwm
**CPU INFO**
Vendor: AMD
Model: AMD Ryzen 5 3600
Physical cores: 6
Logical cores: 12
**MEMORY INFO**
RAM: 15.9 GB
Swap: OFF
**GPU INFO**
Vendor: NVIDIA Corporation
OpenGL Renderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
OpenGL Version: 3.6.0 NVIDIA 530.41.03
OpenGL Core: 3.6.0 NVIDIA 530.41.03
OpenGL ES: OpenGL ES 3.2 NVIDIA 530.41.03
Vulkan: Supported

**Comment by hwsmm** [comment]
Use a tagged version for now

I am mostly testing master branch on Windows for now, I'll try working on Linux after some time

**Comment by hwsmm** [comment]
I tried fixing it in the latest commit, can you give it a try?

**Comment by qubiX00** [comment]
Sure

**Comment by qubiX00** [comment]
I tried it, and it works perfect, but i still have a small notice, even though i have libzip installed it still says that it could find dependency but when i change in meson.build from dependency("zip") to dependency("libzip") it works how it should so i'd also recommend you change that, but thanks!

**Comment by hwsmm** [comment]
I just fixed it :D thanks for using!
You can close this issue if you want
