### ISSUE TITLE
ERROR: Neither source directory 'build' nor build directory None contain a build file meson.build.

### ISSUE THREAD

**Issue by alice4355** [hwsmm/cosutrainer#5]
i don't understand well the steps i have to follow. I'm on fedora 40 KDE plasma

**Comment by hwsmm** [comment]
Is there any reason you want to build from source? You need to run these commands in the source directory.

This program is also available in binaries if you just want to use:
- You can download an AppImage package [here](https://github.com/hwsmm/cosutrainer/releases/tag/0.12).
- I just added a package for Fedora 40 [here](https://software.opensuse.org//download.html?project=home%3Ahwsnemo%3Apackaged-wine-osu&package=cosu-trainer), too.

**Comment by alice4355** [comment]
ooh thank you that would be better because i'm pretty new to linux (4th day using it) so i'm not good at those terminal codes yet

**Comment by hwsmm** [comment]
Good to hear that :D
